### PR TITLE
accomodate the code to v4 upgrade + add a walkthrough video

### PR DESCRIPTION
**Pull request by aaalexlit**
additionally:
- allow to set the number of ingested images
- improve streamlit app layout and usability
- refactor

### CODE REVIEW

**Comment by aaalexlit** [comment]
@iamleonie whenever you can have a look
thanks!

**Comment by iamleonie** [comment]
@aaalexlit Thank you for continuously working on this cool project. 

Question regarding the dataset:
If the dataset is not specifically created by you, it would be better to keep the download instructions and not have the dataset in the repository directly and avoid any potential licensing issues.

**Comment by aaalexlit** [comment]
yes, I also had doubts about the dataset. Theoretically, the license on the [Kaggle Dataset page](https://www.kaggle.com/datasets/abhijeetbhilare/world-cuisines) is [open data commons](https://opendatacommons.org/licenses/dbcl/1-0/) and it's very permissive.
do you think it's still not a good idea to add the dataset?

**Comment by iamleonie** [comment]
If it's a dataset available on Kaggle, let's keep it as download instructions - that way the person who created and uploaded the dataset also gets credit for it and we don't duplicate datasets in this repo.

**Comment by aaalexlit** [comment]
sure!
done

**Review by iamleonie — APPROVED** [review]

**Comment by iamleonie** [comment]
Awesome. It's merged. 
Thank you so much for your contribution! We will share it on our socials in the coming days!

**Comment by aaalexlit** [comment]
Great, thank you!

**Pull request merged**
