### PR TITLE
First iteration of a new similar image search demo

### PR DESCRIPTION
**Pull request by aaalexlit**
@iamleonie, the readme is still WIP and the tests are missing but all the code should work

### CODE REVIEW

**Comment by iamleonie** [comment]
Hi Alex, Thank you for another amazing contribution.
I just tested it and ran into one issue in the last step:

When running `streamlit run app.py` I get the error:
> ModuleNotFoundError: No module named 'streamlit_image_select'
which is weird because it is defined in the requirements.txt and I installed it in a clean venv, as you described...

I also tried the full procedure after changing 'streamlit_image_select' to 'streamlit-image-select' in the requirements.txt but no success. Is there anything else required to run this?

**Comment by aaalexlit** [comment]
@iamleonie Nothing else should be required...
I'm afraid I can't reproduce. 
I tried it on my local from scratch just following the instructions in the readme, I tried it on github codespaces for scratch, and it works for me everywhere...

Can you please double-check that you're running `streamlit run app.py` in the created `venv`? 
Or maybe try it from the codespaces?

**Comment by aaalexlit** [comment]
I just pinned dependencies versions, probably it will fix the problem

**Review by iamleonie — APPROVED** [review]

**Comment by iamleonie** [comment]
Thank you for the investigation. I merged the PR.

**Pull request merged**
